{
    "Target": {
        "EntitySet": "TravelagencyCollection",
        "Service": "/MDK/Services/service1.service",
        "ReadLink": "{@odata.readLink}"
    },
    "OnSuccess": "/MDK/Actions/DeleteEntitySuccessMessage.action",
    "OnFailure": "/MDK/Actions/DeleteEntityFailureMessage.action",
    "ActionResult": {
        "_Name": "delete"
    },
    "_Type": "Action.Type.ODataService.DeleteEntity"
}